export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const CHANGE_HEADER_THEME = "CHANGE_HEADER_THEME";
export const SET_PRICING = "SET_PRICING";
export const SET_MODAL_OPENED = "SET_MODAL_OPENED";
export const SET_MODAL_NAME_OPENED = "SET_MODAL_NAME_OPENED";
